---
options:
  triliovault-ip:
    type: string
    default:
    description: TrilioVault IP Address
  nfs-shares:
    type: string
    default:
    description: NFS Shares mount source path
  nfs-options:
    type: string
    default: nolock,soft,timeo=180,intr,lookupcache=none
    description: NFS Options
